export {
  calculateUnitDiscountOffer,
  getUnitDiscountDisplayState,
  getUnitDiscountedRemaining,
  getUnitDiscountInvoiceDateChangeNotice,
  getUnitDiscountPayByDate,
  normalizeUnitDiscountOfferJson,
  parseUnitDiscountOffer,
  resolveUnitDiscountOffer,
  UNIT_DISCOUNT_PAYMENT_WINDOW_DAYS,
  type UnitDiscountBreakdownLine,
  type UnitDiscountDateChangeNotice,
  type UnitDiscountOfferSnapshot,
  type UnitDiscountSettingSnapshot,
} from "./unit-discount-shared";
