export {
  calculateShippingDiscountOffer,
  calculateUnitDiscountOffer,
  DISCOUNT_KIND_SHIPPING_CREDIT,
  DISCOUNT_KIND_UNIT_PERCENT,
  formatShippingThresholdSummary,
  getDiscountKind,
  getUnitDiscountDisplayState,
  getUnitDiscountedRemaining,
  getUnitDiscountInvoiceDateChangeNotice,
  getUnitDiscountPayByDate,
  normalizeUnitDiscountOfferJson,
  parseShippingDiscountOffer,
  parseShippingThresholds,
  parseUnitDiscountOffer,
  resolveUnitDiscountOffer,
  UNIT_DISCOUNT_PAYMENT_WINDOW_DAYS,
  validateShippingThresholds,
  type DiscountKind,
  type ShippingDiscountOfferSnapshot,
  type ShippingDiscountThreshold,
  type UnitDiscountBreakdownLine,
  type UnitDiscountDateChangeNotice,
  type UnitDiscountOfferSnapshot,
  type UnitDiscountSettingSnapshot,
} from "./unit-discount-shared";
